# {{ ansible_managed | comment(decoration="# ") }}
---
version: "2.4"

networks:
  data:
    external: true

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo
    volumes:
      - "{{ data_path }}/mongo:/data/db"
    networks:
      - data

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mysql
    mem_reservation: 512M
    mem_limit: 1G
    volumes:
      - "{{ data_path }}/mysql:/var/lib/mysql"
      - "{{ data_path }}/config/mysql.conf:/etc/mysql/conf.d/my.cnf"
    networks:
      - data

  postgres:
    image: postgres:12.2
    restart: unless-stopped
    container_name: postgres
    mem_limit: 512M
    volumes:
      - "{{ data_path }}/postgres:/var/lib/postgresql/data"
    networks:
      - data

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    mem_limit: 512M
    networks:
      - data
