---
- name: Create storage directory
  become: yes
  file:
    path: "{{ data_path }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  with_items:
    - config
    - ghost

- name: Copy configuration file
  template:
    src: ghost.json
    dest: "{{ data_path }}/config/ghost.json"
    mode: "0644"

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: "{{ data_path }}/ghost/Dockerfile"
    mode: "0644"

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_path }}/docker-compose.yml"
    mode: "0644"

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_path }}"
    pull: true
    remove_orphans: true
