---
- name: Create config directory
  become: yes
  file:
    path: "{{ data_path }}/config"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Create data storage directories
  become: yes
  file:
    path: "{{ data_path }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "999"
    group: "999"
  with_items:
    - mongo
    - mysql
    - postgres

- name: Copy MySQL configuration file
  template:
    src: mysql.conf
    dest: "{{ data_path }}/config/mysql.conf"
    mode: "0644"
    owner: "999"
    group: "999"

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_path }}/docker-compose.yml"
    mode: "0644"

- name: Create Docker network
  community.docker.docker_network:
    name: data

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_path }}"
    pull: true
    remove_orphans: yes
