---
- name: Create storage directories
  become: yes
  file:
    path: "{{ data_path }}/{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  with_items:
    - mongo
    - mysql
    - postgres
    - config

- name: Copy configuration files
  template:
    src: "{{ item }}"
    dest: "{{ data_path }}/config/{{ item }}"
    mode: "0644"
  with_items:
    - mysql.conf
    - docker-compose.yml

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_path }}/docker-compose.yml"
    mode: "0644"

- name: Create Docker network
  community.docker.docker_network:
    name: data

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_path }}"
    pull: true
    remove_orphans: yes
