---
- name: Install and configure Docker
  become: true
  tags: docker
  block:
    - name: Remove old Docker packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        cache_valid_time: 3600

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Read OS version
      command: lsb_release -cs
      changed_when: no
      register: os_version

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ os_version.stdout }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        cache_valid_time: 3600
        state: latest

    - name: Add ansible user to docker group
      user:
        name: "{{ remote_user }}"
        groups:
          - docker
        append: yes

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose
        state: present
