---
- name: Create storage directory
  become: yes
  file:
    path: "{{ data_path }}/config"
    state: directory
    mode: "0755"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Copy configuration files
  template:
    src: "{{ item }}"
    dest: "{{ data_path }}/config/{{ item }}"
    mode: "0644"
  with_items:
    - matomo.config.php
    - php.ini

- name: Copy Docker Compose definition file
  template:
    src: docker-compose.yml
    dest: "{{ data_path }}/docker-compose.yml"
    mode: "0644"

- name: Start the stack with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ data_path }}"
    pull: true
    remove_orphans: true

- name: Install the Matomo cron
  cron:
    name: "matomo cron"
    minute: "*/5"
    job: "docker start matomo_cron"
