---
- name: Configure the data stores
  hosts: all
  tags: data
  roles: [app_data]

- name: Configure the reverse proxy
  hosts: all
  tags: proxy
  roles: [app_proxy]

- name: Configure the Docker registry
  hosts: all
  tags: registry
  roles: [app_docker_registry]

- name: Configure the website
  hosts: all
  tags: website
  roles: [app_website]
