---
- name: Configure the data stores
  hosts: web
  tags: data
  roles: [app_data]

- name: Configure the reverse proxy
  hosts: web
  tags: proxy
  roles: [app_proxy]

- name: Configure the SMTP relay
  hosts: web
  tags: smtp
  roles: [app_smtp]

- name: Configure the Docker registry
  hosts: web
  tags: registry
  roles: [app_docker_registry]

- name: Configure the website
  hosts: web
  tags: website
  roles: [app_website]

- name: Configure Commento
  hosts: web
  tags: commento
  roles: [app_commento]

- name: Configure Ghost
  hosts: web
  tags: ghost
  roles: [app_ghost]

- name: Configure Matomo
  hosts: web
  tags: matomo
  roles: [app_matomo]
